version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: t51g85F54
      POSTGRES_USER: RENAN
      POSTGRES_DB: sch1
    expose:
      - 5432

networks:
  default:
    name: postgre-service_default